default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  port: <%= ENV['POSTGRESQL_PORT'].to_i %>  # Convierte a entero si es neces
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: rails_job_plataform_development
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
production:
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_HOST'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
