default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_job_plataform_development
  username: vagrant
  password: ror2024
  host: localhost
  port: 5432

test:
  <<: *default
  database: rails_job_plataform_development
  username: vagrant
  password: ror2024
  host: localhost
  port: 5432

production:
  <<: *default
  database: rails_job_plataform_development
  username: rails_job_plataform
  password: <%= ENV["JOB_PLATFORM_DATABASE_PASSWORD"] %>
